sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t georgimitev/docker-react .

script:
  - docker run --rm georgimitev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-173515354855"
  bucket_path: "docker"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"